### ISSUE TITLE
JS error in editor.js?

### ISSUE THREAD

**Issue by stheophil** [stheophil/wahlversprechen#44]
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined /assets/javascripts/app.min.js:61

**Comment by stheophil** [comment]
The problem is in `prefs.js:187`. The tags are loaded immediately and then we start looking for the page elements (which don't exist unless it is actually `/admin/prefs` page): 

```
addDelegatingEventHandler();
var tagsDeferred = loadTags();

// Start loading tags and template ASAP,
// but only render them when the DOM is ready.
$.when(loadTagsListEntryTemplate(), tagsDeferred).done(...)
```

Either we should load the tags when we _are_ on the `/admin/prefs` page or we split this into its own require.js entry-point which is only loaded on `/admin/prefs`

**Comment by mknecht** [comment]
Meh, right. That was still unresolved.

Logic what code to run on which site needs to have an understanding of the whole app, as it is orchestrating. Therefore, it ought to be separate from domain logic.
In other words, specific code should be able to assume that it's _meant_ to run, because it is being run.

Implementation of that separation could go either with separate require.js entry points, or by some middle layer inbetween. If we expect all sites to share tons of initialization logic, we might want to go with the latter. You know the app better.
