### ISSUE TITLE
object theophil is not a member of package net

### ISSUE THREAD

**Issue by JarnoRFB** [stheophil/wahlversprechen#58]
When trying to set up the app according to the instructions in the docs I get this error on initial compilation `object theophil is not a member of package net` in the file `/app/controllers/FeedDaemon.scala`.

**Comment by stheophil** [comment]
You need to check out the https://github.com/stheophil/RelatedTexts project as well. I turned this into a separate project -- maybe prematurely. It contains the code that tries to find the election promises that best match a set of news articles pulled from RSS feeds. That was a cool functionality but the implementation was far from perfect.

Getting the article full-text is already pretty error prone. There are commercial libraries that do this much better of course. I don't know if good free alternatives exist yet. Matching articles to the campaign promises is hard too because many of them are very short. 

(Or you can simply disable the `FeedDaemon` to get going.)
